### ISSUE TITLE
Sign up a new user with Twitter doesn't work.

### ISSUE THREAD

**Issue by elado** [AlexanderZaytsev/domp#7]
Sign up leads to Twitter, then to the sign up form with Email/password.
After submitting that form, no record is being added to the user_authentications table.
If I sign in with Facebook, it does add a record. If I then sign in with twitter, as a logged in user, it also adds a record.

**Comment by AlexanderZaytsev** [comment]
This is because Twitter doesn't return the user's email (and email is required by Devise, so that user is not being created). `domp` was created to be a boilerplate which should give you a flexbile way to customize it. In your case with twitter, you might redirect a user to a different page and ask for an email.
